//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvSayfam.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities2 : DbContext
    {
        public DbCvEntities2()
            : base("name=DbCvEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Deneyimlerim> Deneyimlerim { get; set; }
        public virtual DbSet<Eğitimlerim> Eğitimlerim { get; set; }
        public virtual DbSet<Hakkımda> Hakkımda { get; set; }
        public virtual DbSet<Hobilerim> Hobilerim { get; set; }
        public virtual DbSet<İletişim> İletişim { get; set; }
        public virtual DbSet<Sertifikalarım> Sertifikalarım { get; set; }
        public virtual DbSet<Yeteneklerim> Yeteneklerim { get; set; }
        public virtual DbSet<TblSosyalMedya> TblSosyalMedya { get; set; }
    }
}
